name: Build and Publish VSIX

on:
  push:
    tags:
      - 'v*' # Trigger only on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build solution with MSBuild
      run: |
        msbuild .\Nivra.DotNetAnalyzers\Nivra.DotNetAnalyzers.Vsix -t:rebuild -verbosity:diag /p:Configuration=Release

    - name: Build and Run Tests
      run: |
        dotnet test .\Nivra.DotNetAnalyzers\Nivra.DotNetAnalyzers.Test\Nivra.DotNetAnalyzers.Test.csproj --configuration Release --no-restore --verbosity normal

    - name: Find VSIX file
      id: find-vsix
      shell: bash
      run: |
        VSIX_OUTPUT_PATH=$(find . -name '*.vsix' | head -n 1)
        if [ -z "$VSIX_OUTPUT_PATH" ]; then
          echo "No VSIX file found."
          exit 1
        fi
        echo "VSIX file found: $VSIX_OUTPUT_PATH"
        echo "vsix_path=$VSIX_OUTPUT_PATH" >> $GITHUB_ENV

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload VSIX to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.vsix_path }}
        asset_name: Nivra.DotNetAnalyzers.vsix
        asset_content_type: application/octet-stream