name: Build and Publish VSIX

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build solution with MSBuild
      run: |
        msbuild .\Nivra.DotNetAnalyzers\Nivra.DotNetAnalyzers.Vsix -t:rebuild -verbosity:diag /p:Configuration=Release

    - name: Build and Run Tests
      run: |
        dotnet test .\Nivra.DotNetAnalyzers\Nivra.DotNetAnalyzers.Test\Nivra.DotNetAnalyzers.Test.csproj --configuration Release --no-restore --verbosity normal

    - name: Install VSIX Publisher
      run: |
        choco install visualstudiovsixinstaller --yes

    - name: Find VSIX file
      id: find-vsix
      env:
        VSIX_OUTPUT_PATH: $(find . -name '*.vsix' | head -n 1)
      run: |
        if [ -z "$VSIX_OUTPUT_PATH" ]; then
          echo "No VSIX file found."
          exit 1
        fi
        echo "::set-output name=vsix_path::$VSIX_OUTPUT_PATH"
        
    - name: Upload VSIX as artifact
      uses: actions/upload-artifact@v4
      with:
        name: VSIX-Artifact-${{ matrix.runs-on }}
        path: ${{ steps.find-vsix.outputs.vsix_path }}